### ISSUE TITLE
Create a 'pre-game checklist'

### ISSUE THREAD

**Issue by binnur** [Spartronics4915/2015-Recycle-Rush#119]
On our wiki, start a pre-game checklist for the drive team. Some items that needs to be included (make sure checklist is in some logical sort order):
- [ ] Version number of our robot code on the driver station
- [ ] Ensure joysticks are numbered correctly (insert values here:)
- [ ] Check camera and critical sensor functions (ex. the elevator cable and limit switch operation)
- [ ] Charge pneumatics (make sure internet cable is part of the driver station)
- [ ] Install new battery
- [ ] Verify correct autonomous game is selected on SmartDashboard
- [ ] Verify full range-of-motion of grabber and elevator
- [ ] Make sure the robot can maneuver in all directions

Outline expected robot placement (in detail) for each autonomous game:
- [ ] elevator position
- [ ] grabber position
- [ ] robot placement (including touching field elements or not!)
